# Generated by Django 3.0.8 on 2020-08-03 08:12

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_list', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('target', models.IntegerField()),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction_history',
            },
        ),
    ]
